Fix incorrect syntax on the java package template, caused by identation.

diff --git a/.github/workflows/ci_java_package.yml b/.github/workflows/ci_java_package.yml
--- a/.github/workflows/ci_java_package.yml
+++ b/.github/workflows/ci_java_package.yml
@@ -170,45 +170,45 @@ jobs:
           MAVEN_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
           MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
           SERVICES_TO_BUILD: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_BUILD }}
-          run: >-
-            git pull origin "${{ inputs.deployable_branch_name }}";
+        run: >-
+          git pull origin "${{ inputs.deployable_branch_name }}";
 
-            for service in ${SERVICES_TO_BUILD[@]}; do
-              echo "Bumping version in the pom.xml file for service: ${service}";
+          for service in ${SERVICES_TO_BUILD[@]}; do
+            echo "Bumping version in the pom.xml file for service: ${service}";
 
-              SERVICE_DIR="${GITHUB_WORKSPACE}/${{ inputs.source_dir_name }}/${service}";
-              POM_FILE="${SERVICE_DIR}/pom.xml";
+            SERVICE_DIR="${GITHUB_WORKSPACE}/${{ inputs.source_dir_name }}/${service}";
+            POM_FILE="${SERVICE_DIR}/pom.xml";
 
-              if [[ ! -f "${POM_FILE}" ]]; then
-                echo "Could not find pom.xml for service '${service}'";
-                exit 1;
-              fi
+            if [[ ! -f "${POM_FILE}" ]]; then
+              echo "Could not find pom.xml for service '${service}'";
+              exit 1;
+            fi
 
-              echo "Found project file: ${PROJ_FILE}";
-              CUR_VERSION=$(mvn -q -f "${POM_FILE}" -DforceStdout help:evaluate -Dexpression=project.version);
-              echo "Current version is: ${CUR_VERSION}";
+            echo "Found project file: ${PROJ_FILE}";
+            CUR_VERSION=$(mvn -q -f "${POM_FILE}" -DforceStdout help:evaluate -Dexpression=project.version);
+            echo "Current version is: ${CUR_VERSION}";
 
-              IFS='.' read -r MAJOR MINOR PATCH <<< "${CUR_VERSION}";
-              if [[ "${VERSION_BUMP_TYPE}" == "major" ]]; then
-                MAJOR=$((MAJOR + 1));
-                MINOR="0";
-                PATCH="0";
-              elif [[ "${VERSION_BUMP_TYPE}" == "minor" ]]; then
-                MINOR=$((MINOR + 1));
-                PATCH="0";
-              elif [[ "${VERSION_BUMP_TYPE}" == "patch" ]]; then
-                PATCH=$((PATCH + 1));
-              else
-                echo "There are services to build, but no supported version bump detected!";
-                exit 1;
-              fi
+            IFS='.' read -r MAJOR MINOR PATCH <<< "${CUR_VERSION}";
+            if [[ "${VERSION_BUMP_TYPE}" == "major" ]]; then
+              MAJOR=$((MAJOR + 1));
+              MINOR="0";
+              PATCH="0";
+            elif [[ "${VERSION_BUMP_TYPE}" == "minor" ]]; then
+              MINOR=$((MINOR + 1));
+              PATCH="0";
+            elif [[ "${VERSION_BUMP_TYPE}" == "patch" ]]; then
+              PATCH=$((PATCH + 1));
+            else
+              echo "There are services to build, but no supported version bump detected!";
+              exit 1;
+            fi
 
-              NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}";
-              echo "New version is: ${NEW_VERSION}";
+            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}";
+            echo "New version is: ${NEW_VERSION}";
 
-              mvn -B -f "${POM_FILE}" versions:set -DnewVersion="${NEW_VERSION}" -DgenerateBackupPoms=false;
-              mvn -B -f "${POM_FILE}" -DskipTests deploy;
-            done
+            mvn -B -f "${POM_FILE}" versions:set -DnewVersion="${NEW_VERSION}" -DgenerateBackupPoms=false;
+            mvn -B -f "${POM_FILE}" -DskipTests deploy;
+          done
 
       - name: Commit version changes
         env:
